# Generated by Django 3.2.7 on 2021-11-04 04:18

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='TireProductModel',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseproduct')),
            ],
            options={
                'abstract': False,
            },
            bases=('product.baseproduct', models.Model),
        ),
        migrations.CreateModel(
            name='WheelProductModel',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseproduct')),
            ],
            options={
                'abstract': False,
            },
            bases=('product.baseproduct', models.Model),
        ),
    ]
