# Generated by Django 3.2.7 on 2021-09-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_baseproduct_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='image',
        ),
    ]
