# Generated by Django 3.2.7 on 2021-09-13 21:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_baseproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
