# Generated by Django 3.2.6 on 2021-08-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0007_remove_option_products'),
        ('product', '0007_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(to='option.Option'),
        ),
    ]
