# Generated by Django 3.2.6 on 2021-08-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
        ('product', '0008_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
