# Generated by Django 3.2.6 on 2021-08-31 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210831_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelProductModel',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseproduct')),
            ],
            bases=('product.baseproduct',),
        ),
    ]
