# Generated by Django 3.2.6 on 2021-09-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_wheelproductmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireProductModel',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.baseproduct')),
            ],
            bases=('product.baseproduct',),
        ),
    ]
