# Generated by Django 3.2.6 on 2021-08-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='option',
        ),
    ]
