# Generated by Django 3.2.6 on 2021-08-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_remove_productoption_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='option_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='option.optionitem'),
        ),
    ]
