# Generated by Django 3.2.6 on 2021-08-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210831_2127'),
        ('option', '0004_brandoption_productbrandoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionitem',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productbrandoption',
            name='brand_option',
        ),
        migrations.RemoveField(
            model_name='productbrandoption',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='option_item',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='product',
        ),
        migrations.RemoveField(
            model_name='option',
            name='name',
        ),
        migrations.AddField(
            model_name='option',
            name='bolt_pattern',
            field=models.CharField(choices=[('RZR', '14x136'), ('CAN', '14x156')], default='RZR', max_length=3),
        ),
        migrations.AddField(
            model_name='option',
            name='publications',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AddField(
            model_name='option',
            name='wheel_size',
            field=models.CharField(choices=[('XS', '14x8'), ('S', '14x10'), ('M', '15x7'), ('L', '15x8'), ('XL', '15x10')], default='M', max_length=2),
        ),
        migrations.DeleteModel(
            name='BrandOption',
        ),
        migrations.DeleteModel(
            name='OptionItem',
        ),
        migrations.DeleteModel(
            name='ProductBrandOption',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
    ]
