# Generated by Django 3.2.6 on 2021-08-31 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0005_auto_20210831_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='publications',
            new_name='products',
        ),
    ]
