# Generated by Django 3.2.6 on 2021-08-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0006_rename_publications_option_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='products',
        ),
    ]
