# Generated by Django 3.2.6 on 2021-09-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('bolt_pattern', models.CharField(choices=[
                 ('RZR', '14x136'), ('CAN', '14x156')], default='RZR', max_length=3)),
                ('unit_price', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(max_length=150)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='variants', to='product.wheelproductmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TireProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(choices=[(28, 'Twenty Eight'), (29, 'Twenty Nine'), (30, 'Thirty'), (
                    31, 'Thirty One'), (32, 'Thirty Two'), (33, 'Thirty Three'), (34, 'Thirty Four'), (35, 'Thirty Five')])),
                ('width', models.IntegerField(choices=[
                 (8, 'Eight'), (9, 'Nine'), (10, 'Ten')])),
                ('rim_circumference', models.IntegerField(choices=[
                 (14, 'Fourteen'), (15, 'Fifteen'), (16, 'Sixteen')])),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='variants', to='product.tireproductmodel')),
            ],
        ),
    ]
