# Generated by Django 3.2.6 on 2021-09-01 17:17

from django.db import migrations, models
import django.db.models.deletion
import product_variant.choices


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_tireproductmodel'),
        ('product_variant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelproductvariant',
            name='size',
            field=models.CharField(choices=[(product_variant.choices.Sizes['XSMALL'], '14x8'), (product_variant.choices.Sizes['SMALL'], '14x10'), (product_variant.choices.Sizes['MEDIUM'], '15x7'), (product_variant.choices.Sizes['LARGE'], '15x8'), (product_variant.choices.Sizes['XLARGE'], '15x10')], default=product_variant.choices.Sizes['MEDIUM'], max_length=2),
        ),
        migrations.CreateModel(
            name='TireProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(choices=[(28, 'Twenty Eight'), (29, 'Twenty Nine'), (30, 'Thirty'), (31, 'Thirty One'), (32, 'Thirty Two'), (33, 'Thirty Three'), (34, 'Thirty Four'), (35, 'Thirty Five')])),
                ('width', models.IntegerField(choices=[(8, 'Eight'), (9, 'Nine'), (10, 'Ten')])),
                ('rim_circumference', models.IntegerField(choices=[(14, 'Fourteen'), (15, 'Fifteen'), (16, 'Sixteen')])),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.tireproductmodel')),
            ],
        ),
    ]
