# Generated by Django 3.2.6 on 2021-09-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelproductvariant',
            name='finish',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
