# Generated by Django 3.2.6 on 2021-09-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0002_wheelproductvariant_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='tireproductvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wheelproductvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
