# Generated by Django 3.2.6 on 2021-09-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0003_auto_20210901_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelproductvariant',
            name='bolt_pattern',
            field=models.CharField(
                choices=[('14x136', 'Rzr'), ('14x156', 'Can')], default='RZR', max_length=6),
        ),

    ]
