# Generated by Django 3.2.6 on 2021-09-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0004_auto_20210901_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default='', max_length=150)),
                ('stock', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='tireproductvariant',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='wheelproductvariant',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='wheelproductvariant',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='wheelproductvariant',
            name='unit_price',
        ),
    ]
