# Generated by Django 3.2.6 on 2021-09-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0005_auto_20210901_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseVariant',
        ),
        migrations.AddField(
            model_name='tireproductvariant',
            name='product_code',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tireproductvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tireproductvariant',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wheelproductvariant',
            name='product_code',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='wheelproductvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wheelproductvariant',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
