# Generated by Django 3.2.7 on 2021-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0006_auto_20210901_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireproductvariant',
            name='height',
            field=models.IntegerField(choices=[(28, 28), (29, 29), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35)]),
        ),
        migrations.AlterField(
            model_name='tireproductvariant',
            name='rim_circumference',
            field=models.IntegerField(choices=[(14, 14), (15, 15), (16, 16)]),
        ),
        migrations.AlterField(
            model_name='tireproductvariant',
            name='width',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10)]),
        ),
    ]
