# Generated by Django 3.2.7 on 2021-09-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0007_auto_20210902_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireproductvariant',
            name='height',
            field=models.IntegerField(choices=[(28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35)]),
        ),
    ]
