# Generated by Django 3.2.7 on 2021-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0008_alter_tireproductvariant_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelproductvariant',
            name='size',
            field=models.CharField(choices=[('14x8', '14x8'), ('14x10', '14x10'), ('15x7', '15x7'), ('15x8', '15x8'), ('15x10', '15x10')], default='15x7', max_length=6),
        ),
    ]
