# Generated by Django 3.2.7 on 2021-09-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_variant', '0009_wheelproductvariant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelproductvariant',
            name='finish',
        ),
    ]
