# Generated by Django 3.2.7 on 2021-10-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_code',
            new_name='variant_id',
        ),
    ]
